# https://taskfile.dev
version: '3'

dotenv: ['../.env']

vars:
  STARTUP_PATH: "./src/Backend.Web"
  PROJECT_PATH: "./src/Backend.Infra"
  MIGRATIONS_DIR: "Migrations"
  DB_CTX_NAME: "BackendDbCtx"

tasks:

  list:
    aliases: [default]
    desc: List all the tasks available.
    cmds:
      - task --list-all

  run:
    aliases: [r]
    desc: Run the project
    cmds:
      - dotnet run --project {{.STARTUP_PATH}} --no-restore
    requires:
      vars: [ ASPNETCORE_ENVIRONMENT, ASPNETCORE_URLS, DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME ]

  migrate:
    aliases: [m]
    desc: Generate & run EF migrations for a given project
    cmds:
      - task: migration:generate
      - task: migration:apply

  migration:generate:
    aliases: [mg]
    desc: Generate EF migrations for a given project
    cmds:
      - dotnet ef migrations add {{.MIGRATION_NAME}} -p {{.PROJECT_PATH}} -s {{.STARTUP_PATH}} -o {{.MIGRATIONS_DIR}} --context {{.DB_CTX_NAME}}
    requires:
      vars: [ MIGRATION_NAME, PROJECT_PATH, STARTUP_PATH, MIGRATIONS_DIR, DB_CTX_NAME ]

  migration:apply:
    aliases: [ma]
    desc: Run EF migrations for a given project
    cmds:
      - dotnet ef database update -p {{.PROJECT_PATH}} -s {{.STARTUP_PATH}} --context {{.DB_CTX_NAME}}
    requires:
      vars: [ PROJECT_PATH, STARTUP_PATH, DB_CTX_NAME]

  restore:
    aliases: [setup]
    desc: Setup/Restore the whole project
    cmds:
      - dotnet restore ./Backend.slnx
