# https://taskfile.dev
version: '3'

dotenv: ['../.env']

vars:
  MIGRATIONS_DIR: "Migrations"

tasks:

  list:
    aliases: [default]
    desc: List all the tasks available.
    cmds:
      - task --list-all

  run:
    aliases: [r]
    desc: Run the project
    cmds:
      - dotnet run
    requires:
      vars: [ ASPNETCORE_ENVIRONMENT, ASPNETCORE_URLS, DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME ]

  migrate:
    aliases: [m]
    desc: Generate & run EF migrations for a given project
    cmds:
      - task: migration:generate
      - task: migration:apply

  migration:generate:
    aliases: [mg]
    desc: Generate EF migrations for a given project
    cmds:
      - dotnet ef migrations add {{.MIGRATION_NAME}} -o {{.MIGRATIONS_DIR}}
    requires:
      vars: [ MIGRATION_NAME, MIGRATIONS_DIR ]

  migration:apply:
    aliases: [ma]
    desc: Run EF migrations for a given project
    cmds:
      - dotnet ef database update
    requires:
      vars: []

  restore:
    aliases: [setup]
    desc: Setup/Restore the whole project
    cmds:
      - dotnet restore ./Backend.slnx
