/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../../routes/__root"
import { Route as LoginRouteImport } from "./../../routes/login"
import { Route as IntroRouteImport } from "./../../routes/intro"
import { Route as IndexRouteImport } from "./../../routes/index"
import { Route as DevIndexRouteImport } from "./../../routes/dev/index"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: "/intro",
  path: "/intro",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: "/dev/",
  path: "/dev/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/intro": typeof IntroRoute
  "/login": typeof LoginRoute
  "/dev/": typeof DevIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/intro": typeof IntroRoute
  "/login": typeof LoginRoute
  "/dev": typeof DevIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/intro": typeof IntroRoute
  "/login": typeof LoginRoute
  "/dev/": typeof DevIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/intro" | "/login" | "/dev/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/intro" | "/login" | "/dev"
  id: "__root__" | "/" | "/intro" | "/login" | "/dev/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntroRoute: typeof IntroRoute
  LoginRoute: typeof LoginRoute
  DevIndexRoute: typeof DevIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/intro": {
      id: "/intro"
      path: "/intro"
      fullPath: "/intro"
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dev/": {
      id: "/dev/"
      path: "/dev"
      fullPath: "/dev/"
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntroRoute: IntroRoute,
  LoginRoute: LoginRoute,
  DevIndexRoute: DevIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
